add watchdog feature, support restart child process throught -r param…
thomas-kl/chik pull request #2
Opened 2018-03-13 10:14 UTC by hubugui

please help review, thanks!

2018-03-14 22:17 UTC, thomas-kl requested changes
Cool submissions, thanks!

In addition to the comments, can you also add the "-r" plus a description to the help text at the start of the main?

2018-03-14 22:17 UTC, thomas-kl commented on chik/chik.cpp
> +		} else
Can you add also braces "{}" for else to have common code-style?

2018-03-14 22:17 UTC, thomas-kl commented on chik/chik.cpp
> +		int restart_child = 0;
Can you use bool instead of int here?

2018-03-14 22:17 UTC, thomas-kl commented on chik/chik.cpp
> +		int i;
Init with "1", just to have a good default in case of later code changes?

2018-03-26 17:28 UTC, merged

2018-03-26 17:31 UTC, thomas-kl commented
Hey! I merged the changes to master, thanks!

2018-03-26 18:19 UTC, thomas-kl commented
Now also released -> v1.2

2018-04-25 07:38 UTC, hubugui commented
Hi, Sorry for I did not follow github recently.

Thanks for your merged!